print("----------------------------------------------------")
print("|                                                   |")
print("|           PROGRAM :Test                           |")
print("|                                                   |")
print("|            Ćwiczymy funkcje print                 |")
print("|            Auto T.Wyczesany                       |")
print("----------------------------------------------------")